from unicodedata import name
from django.urls import path
from .views import *


urlpatterns = [
    path('api/get_dems/', get_new_demands, name="get_new_demands" ),
    path('pay/<str:token>/', pay, name="pay"),
    path('pay_success/<str:token>/', pay_success, name="pay_succes"),
    path('api/satisfied/<int:pk>/', set_satisfied, name="set_satisfied"),
    path('api/rembourse/<int:pk>/', set_rembour, name="set_rembour"),
    path('api/delete/<int:pk>/', delete_dem, name="delete_dem"),
    path('api/get_tree_cats/', get_tree_cats, name="get_tree_cats"),
    path('api/register_demand/', register_demand, name="v2_register_demand"),
    path('api/authenticate_seller/', authenticate_seller, name="authenticate_seller"),
    path('api/get_payments/', get_payments, name="get_payments"),
    path('ping/', ping, name="ping"),
    path('api/register_seller/', register_seller, name="register_seller"),
    path('api/get_seller_state/', get_seller_state, name="get_seller_state"),
    path('api/get_sparams/', get_sparams, name="get_sparams"),
    path('api/set_spicture/', set_spicture, name="set_spicture"),
    path('api/check_password/', check_password, name="check_password"),
    path('api/update_info/', update_info, name="update_info"),
    path('api/update_password/', update_password, name="update_password"),
    path('api/set_momo/', set_momo, name="set_momo"),
    path('api/upload_img/', upload_img, name="upload_img"),
    path('api/pupload_img/', pupload_img, name="upload_img"),
    path('api/create_momo/', create_momo, name="create_momo"),
    path('api/get_spays/', get_spays, name="get_spays"),
    path('api/encaisser/', encaisser, name ="encaisser"),
    path('api/sub_prod/<int:id>/', sub_prod, name="sub_prod"),
    path('api/prods_mm/<int:id>/', prods_mm, name="prods_mm"),
    path('api/delete_th/', delete_th, name="delete_th"),
    path('api/create_prod/', create_prod, name="create_prod"),
    path('api/add_sub/', add_sub, name="add_sub"),
    path('api/sold_prods/', sold_prods, name="sold_prods"),
    path('api/has_paccount/', has_paccount, name="has_paccount"),
    path('api/register_patner/', register_patner, name="register_patner"),
    path('api/get_patner/', get_patner, name="get_patner"),
    path('api/get_pparams/', get_pparams, name="get_pparams"),
    path('api/set_ppicture/', set_ppicture, name="set_ppicture"),
    path('api/pupdate_info/', pupdate_info, name="pupdate_info"),
    path('api/pupdate_password/', pupdate_password, name="pupdate_password"),
    path('api/get_ppays/', get_ppays, name="get_ppays"),
    path('api/get_subpatner/<int:id>/', get_subpatner, name="get_subpatner"),
    path('api/padd_sub/', padd_sub, name="padd_sub"),
    path('api/get_dis/', get_dis, name="get_dis"),
    path('api/get_mydis/<int:id>/', get_mydis, name="get_mydis"),
    path('api/get_recoms/<int:id>/', get_recoms, name="get_recoms"),
    path('api/delete_me/<int:id>/', delete_me, name="delete_me"),
    path('api/enable_payment/<int:id>/', enable_payment, name="enable_payment"),
    path('api/set_discuss/<int:id>/', set_discuss, name="set_discuss"),
    path('api/disable_payment/<int:id>/', disable_payment, name="disable_payment"),
    path('api/get_state/<int:id>/', get_state, name="get_state"),
    path('api/pprods_mm/<int:id>/', pprods_mm, name="pprods_mm"),
    path('api/delete_sp/<int:pk>/', delete_sp, name="delete_sp"),
    path("api/get_version/", get_version, name="get_version")
]