# Generated by Django 3.2.6 on 2022-11-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221104_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=250, null=True)),
                ('seller', models.CharField(blank=True, max_length=250, null=True)),
                ('picture', models.FileField(blank=True, null=True, upload_to='feedback/')),
                ('text', models.TextField(blank=True, max_length=250, null=True)),
                ('rank', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ZawadiDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=250, null=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
