# Generated by Django 3.2.6 on 2022-11-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20221104_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='accounts/'),
        ),
    ]
