# Generated by Django 3.2.6 on 2022-11-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_selleraccount_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekcustom',
            name='next',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weekcustom',
            name='prev',
            field=models.IntegerField(default=0),
        ),
    ]
