# Generated by Django 4.0.4 on 2022-11-06 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20221106_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekcustom',
            name='max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weekcustom',
            name='max_urg',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AbnFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.CharField(blank=True, max_length=150, null=True)),
                ('total', models.IntegerField(default=0)),
                ('total_urg', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('expired', models.DateField(blank=True, null=True)),
                ('transaction_id', models.TextField(blank=True, null=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abns', to='app.selleraccount')),
            ],
        ),
    ]
