# Generated by Django 4.0.4 on 2022-11-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_weekcustom_max_weekcustom_max_urg_abnfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='type_of',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='selleraccount',
            name='status',
            field=models.CharField(blank=True, default='off', max_length=150, null=True),
        ),
    ]
