# Generated by Django 4.0.4 on 2022-11-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_selleraccount_type_of_alter_selleraccount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdemand',
            name='is_out',
            field=models.BooleanField(default=True),
        ),
    ]
