# Generated by Django 4.0.4 on 2022-11-07 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_clientdemand_is_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='abnfeature',
            name='rest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='abnfeature',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientdemand',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='speed',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.CharField(blank=True, max_length=150, null=True)),
                ('value2', models.CharField(blank=True, max_length=150, null=True)),
                ('day', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
