# Generated by Django 4.0.4 on 2022-11-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_abnfeature_rest_abnfeature_status_clientdemand_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abnfeature',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='abnfeature',
            name='status',
        ),
        migrations.RemoveField(
            model_name='selleraccount',
            name='expired_date',
        ),
        migrations.RemoveField(
            model_name='selleraccount',
            name='status',
        ),
        migrations.AddField(
            model_name='abnfeature',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='abn_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='rest',
            field=models.IntegerField(default=0),
        ),
    ]
