# Generated by Django 4.0.4 on 2022-11-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_abnfeature_expired_remove_abnfeature_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abnfeature',
            name='rest',
        ),
    ]
