# Generated by Django 4.0.4 on 2022-11-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_abnfeature_rest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdemand',
            name='is_out',
            field=models.BooleanField(default=False),
        ),
    ]
