# Generated by Django 4.0.4 on 2022-11-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_clientdemand_is_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekcustom',
            name='demandes',
            field=models.ManyToManyField(blank=True, related_name='weeks_in', to='app.clientdemand'),
        ),
    ]
