# Generated by Django 3.2.6 on 2022-11-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_weekcustom_demandes'),
    ]

    operations = [
        migrations.AddField(
            model_name='abnfeature',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
