# Generated by Django 3.2.6 on 2022-11-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20221111_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('is_checked', models.BooleanField(default=False)),
            ],
        ),
    ]
