# Generated by Django 3.2.6 on 2022-11-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_admintoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='abnfeature',
            name='is_freed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='has_freed',
            field=models.BooleanField(default=False),
        ),
    ]
