# Generated by Django 3.2.6 on 2022-11-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20221112_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selleraccount',
            name='category',
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='sellers', to='app.Category'),
        ),
    ]
