# Generated by Django 3.2.6 on 2022-11-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20221117_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdemand',
            name='budget',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='clientdemand',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
