# Generated by Django 3.2.6 on 2022-11-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20221120_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdemand',
            name='num_vend',
            field=models.IntegerField(default=5),
        ),
    ]
