# Generated by Django 3.2.6 on 2022-11-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_clientdemand_num_vend'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdemand',
            name='quart',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientdemand',
            name='slug',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='default_price',
            field=models.IntegerField(blank=True, default=2500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='quart',
            field=models.TextField(blank=True, null=True),
        ),
    ]
