# Generated by Django 3.2.6 on 2022-12-02 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20221126_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='sub_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='app.subcategory'),
        ),
    ]
