# Generated by Django 3.2.6 on 2022-12-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_subcategory_sub_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdemand',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
