# Generated by Django 3.2.6 on 2022-12-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_clientdemand_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
