# Generated by Django 3.2.6 on 2023-01-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_selleraccount_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdemand',
            name='clicked',
            field=models.ManyToManyField(blank=True, related_name='has_clicked', to='app.SellerAccount'),
        ),
        migrations.AlterField(
            model_name='clientdemand',
            name='num_vend',
            field=models.IntegerField(default=3),
        ),
    ]
