# Generated by Django 3.2.6 on 2023-01-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20230103_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='dprice',
            field=models.IntegerField(default=75),
        ),
    ]
