# Generated by Django 3.2.6 on 2023-01-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_category_dprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='damount',
            field=models.IntegerField(blank=True, default=250, null=True),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='damount_init',
            field=models.IntegerField(blank=True, default=250, null=True),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='dprice',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
    ]
