# Generated by Django 3.2.6 on 2023-01-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20230109_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='dm_alert',
            field=models.BooleanField(default=False),
        ),
    ]
