# Generated by Django 3.2.6 on 2023-01-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_selleraccount_dm_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='format_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
