# Generated by Django 3.2.6 on 2023-01-28 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_selleraccount_format_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(blank=True, max_length=150, null=True)),
                ('full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ident', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('money', models.IntegerField(blank=True, default=0, null=True)),
                ('current', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('tof', models.FileField(blank=True, null=True, upload_to='')),
                ('act_err', models.TextField(blank=True, null=True)),
                ('veracity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('montant', models.IntegerField(blank=True, null=True)),
                ('solded', models.BooleanField(default=False)),
                ('parrain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retraits', to='app.parrain')),
            ],
        ),
        migrations.AddField(
            model_name='clientdemand',
            name='parrain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dems', to='app.parrain'),
        ),
    ]
