# Generated by Django 3.2.6 on 2023-01-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20230128_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parrain',
            name='veracity',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
