# Generated by Django 3.2.6 on 2023-01-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_parrain_veracity'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdemand',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
