# Generated by Django 3.2.6 on 2023-02-16 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_clientdemand_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.myfiles'),
        ),
        migrations.AddField(
            model_name='label',
            name='picture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.myfiles'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='picture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.myfiles'),
        ),
    ]
