# Generated by Django 3.2.6 on 2023-03-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20230216_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='prefix',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
