# Generated by Django 3.2.6 on 2023-03-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_subcategory_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='prefix',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
