# Generated by Django 3.2.6 on 2023-01-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='whatsapp_title',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
    ]
