# Generated by Django 3.2.6 on 2023-01-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articles_whatsapp_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
