# Generated by Django 3.2.6 on 2023-02-16 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appv2', '0002_clientpayment_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientpayment',
            name='receipt',
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remboursements', to='appv2.demand')),
            ],
        ),
    ]
