# Generated by Django 3.2.6 on 2023-02-17 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appv2', '0003_auto_20230216_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remboursement',
            old_name='dem',
            new_name='demand',
        ),
    ]
