# Generated by Django 3.2.6 on 2023-02-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20230216_0456'),
        ('appv2', '0004_rename_dem_remboursement_demand'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='ssubs',
            field=models.ManyToManyField(blank=True, null=True, to='app.SubCategory'),
        ),
    ]
