# Generated by Django 3.2.6 on 2023-02-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appv2', '0005_demand_ssubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='currency',
            field=models.CharField(blank=True, default='XOF', max_length=10, null=True),
        ),
    ]
