# Generated by Django 3.2.6 on 2023-02-27 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20230216_0456'),
        ('appv2', '0006_alter_demand_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoMoCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('number', models.CharField(blank=True, max_length=150, null=True)),
                ('piece', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.myfiles')),
            ],
        ),
        migrations.CreateModel(
            name='SellerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.BigIntegerField(default=0)),
                ('total_solde', models.BigIntegerField(default=0)),
                ('current_momo', models.BigIntegerField(default=0)),
                ('momos', models.ManyToManyField(blank=True, related_name='seller_s', to='appv2.MoMoCompte')),
                ('seller', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='app.selleraccount')),
            ],
        ),
        migrations.AddField(
            model_name='discussion',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discussion',
            name='rpatner',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patner',
            name='current_momo',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patner',
            name='is_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patner',
            name='picture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.myfiles'),
        ),
        migrations.AddField(
            model_name='patner',
            name='solde',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patner',
            name='total_solde',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patner',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='sold_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remboursement',
            name='clientpay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='appv2.clientpayment'),
        ),
        migrations.AddField(
            model_name='remboursement',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='demand',
            name='available_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='ssubs',
            field=models.ManyToManyField(blank=True, to='app.SubCategory'),
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='patner',
        ),
        migrations.AddField(
            model_name='discussion',
            name='patner',
            field=models.ManyToManyField(blank=True, related_name='discussions', to='appv2.Patner'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='products_prop',
            field=models.ManyToManyField(blank=True, related_name='is_props_for', to='appv2.Products'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='sold',
            field=models.ManyToManyField(blank=True, related_name='sold_in', to='appv2.Products'),
        ),
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livraison', models.TextField(blank=True, null=True)),
                ('products', models.ManyToManyField(blank=True, related_name='subs_state', to='appv2.Products')),
                ('seller_s', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='appv2.sellerstate')),
                ('subs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs_sellers', to='app.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SellerPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('montant', models.BigIntegerField(blank=True)),
                ('type_of', models.CharField(blank=True, max_length=150, null=True)),
                ('transaction_id', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, default='En cours', max_length=150)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('seller_s', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='appv2.sellerstate')),
            ],
        ),
        migrations.CreateModel(
            name='PatnerTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=150, null=True)),
                ('typ', models.CharField(blank=True, max_length=150, null=True)),
                ('sub_p', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='appv2.subproduct')),
            ],
        ),
        migrations.CreateModel(
            name='PatnerSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mysubs', to='appv2.patner')),
                ('subs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patners', to='app.subcategory')),
                ('templates', models.ManyToManyField(blank=True, related_name='in_subs', to='appv2.PatnerTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='PatnerPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('montant', models.BigIntegerField(blank=True)),
                ('type_of', models.CharField(blank=True, max_length=150, null=True)),
                ('transaction_id', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, default='En cours', max_length=150)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('patner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='appv2.patner')),
            ],
        ),
        migrations.AddField(
            model_name='patner',
            name='momos',
            field=models.ManyToManyField(blank=True, related_name='patners', to='appv2.MoMoCompte'),
        ),
    ]
