# Generated by Django 3.2.6 on 2023-03-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appv2', '0007_auto_20230227_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='unique_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
