# Generated by Django 3.2.6 on 2023-03-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appv2', '0008_demand_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='templates',
            field=models.ManyToManyField(blank=True, related_name='discussions', to='appv2.PatnerTemplate'),
        ),
    ]
