# Generated by Django 3.2.6 on 2023-03-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appv2', '0009_discussion_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='payment_plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
