# Generated by Django 3.2.6 on 2023-03-20 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appv2', '0010_discussion_payment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='patnerpay',
            name='dis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patner_pays', to='appv2.discussion'),
        ),
        migrations.AddField(
            model_name='sellerpay',
            name='dis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_pays', to='appv2.discussion'),
        ),
        migrations.AlterField(
            model_name='patnerpay',
            name='montant',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sellerpay',
            name='montant',
            field=models.FloatField(blank=True),
        ),
    ]
